services:
  redis:
    image: redis:latest
    ports:
      - "46379:6379"
    volumes:
      - redis-data:/data
  
  postgres:
    image: postgres:latest
    ports:
      - "45432:5432"
    volumes:
      - postgres-data:/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres


  chatbot-web:
    build:
      context: ./chatbot-web
      dockerfile: Dockerfile
    ports:
      - "43000:3000"
    volumes:
      - ./chatbot-web/src:/app/src:ro
      - ./chatbot-web/public:/app/public:ro
      - ./chatbot-web/package.json:/app/package.json:ro
      - ./chatbot-web/package-lock.json:/app/package-lock.json:ro
      - ./chatbot-web/next.config.js:/app/next.config.js:ro
      - ./chatbot-web/tsconfig.json:/app/tsconfig.json:ro
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      
  chatbot-api:
    build:
      context: ./chatbot-api
      dockerfile: Dockerfile
    ports:
      - "48000:8000"

  chatbot-nlu:
    build:
      context: ./chatbot-nlu
      dockerfile: Dockerfile
    ports:
      - "45005:5005"


volumes:
  redis-data:
  postgres-data:
