[project]
name = "api-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.110.0",
    "uvicorn>=0.28.0",
    "websockets>=12.0",
    "httpx>=0.26.0",
    "pydantic>=2.6.0",
]
